Metrics/BlockLength:
  Exclude:
    - 'app/graphql/types/**/*'
    - 'app/graphql/mutations/**/*'

Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - 'vendor/**/*'
