---
version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: doctalk-api_test
          RAILS_ENV: test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: doctalk-api_test
          POSTGRES_DB: doctalk-api_test
          POSTGRES_PASSWORD: ""
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v2-dependencies-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
  deploy:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/repo
    steps:
      - checkout
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "e8:37:db:c5:e5:f7:7a:f9:a9:d9:4b:e5:a5:a2:0e:e3"
      - deploy:
          command: |
            git remote add heroku https://git.heroku.com/doctalk-api-prod.git
            git push heroku master
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
