default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: doctalk-api_dev

test:
  <<: *default
  database: doctalk-api_test

production:
  <<: *default
  database: doctalk-api_prod
