Specialty.find_or_create_by!(title: "Acupuntura")
Specialty.find_or_create_by!(title: "Imunologia")
Specialty.find_or_create_by!(title: "Anestesiologia")
Specialty.find_or_create_by!(title: "Angiologia")
Specialty.find_or_create_by!(title: "Oncologia")
Specialty.find_or_create_by!(title: "Cardiologia")
Specialty.find_or_create_by!(title: "Cirurgia Cardiovascular")
Specialty.find_or_create_by!(title: "Cirurgia da Mão")
Specialty.find_or_create_by!(title: "Cirurgia de cabeça e pescoço")
Specialty.find_or_create_by!(title: "Cirurgia do Aparelho Digestivo")
Specialty.find_or_create_by!(title: "Cirurgia Geral")
Specialty.find_or_create_by!(title: "Cirurgia Pediátrica")
Specialty.find_or_create_by!(title: "Cirurgia Plástica")
Specialty.find_or_create_by!(title: "Cirurgia Torácica")
Specialty.find_or_create_by!(title: "Cirurgia Vascular")
Specialty.find_or_create_by!(title: "Coloproctologia")
Specialty.find_or_create_by!(title: "Dermatologia")
Specialty.find_or_create_by!(title: "Endocrinologia e Metabologia")
Specialty.find_or_create_by!(title: "Endoscopia")
Specialty.find_or_create_by!(title: "Gastroenterologia")
Specialty.find_or_create_by!(title: "Genética médica")
Specialty.find_or_create_by!(title: "Geriatria")
Specialty.find_or_create_by!(title: "Ginecologia e obstetrícia")
Specialty.find_or_create_by!(title: "Hematologia e Hemoterapia")
Specialty.find_or_create_by!(title: "Homeopatia")
Specialty.find_or_create_by!(title: "Infectologia")
Specialty.find_or_create_by!(title: "Mastologia")
Specialty.find_or_create_by!(title: "Medicina de Família e Comunidade")
Specialty.find_or_create_by!(title: "Medicina do Trabalho")
Specialty.find_or_create_by!(title: "Medicina do Tráfego")
Specialty.find_or_create_by!(title: "Medicina Esportiva")
Specialty.find_or_create_by!(title: "Medicina Física e Reabilitação")
Specialty.find_or_create_by!(title: "Medicina Intensiva")
Specialty.find_or_create_by!(title: "Medicina Legal e Perícia Médica ou medicina forense")
Specialty.find_or_create_by!(title: "Medicina Nuclear")
Specialty.find_or_create_by!(title: "Medicina Preventiva e Social")
Specialty.find_or_create_by!(title: "Nefrologia")
Specialty.find_or_create_by!(title: "Neurocirurgia")
Specialty.find_or_create_by!(title: "Neurologia")
Specialty.find_or_create_by!(title: "Nutrologia")
Specialty.find_or_create_by!(title: "Obstetrícia")
Specialty.find_or_create_by!(title: "Oftalmologia")
Specialty.find_or_create_by!(title: "Ortopedia e Traumatologia")
Specialty.find_or_create_by!(title: "Otorrinolaringologia")
Specialty.find_or_create_by!(title: "Patologia")
Specialty.find_or_create_by!(title: "Patologia Clínica Medicina laboratorial")
Specialty.find_or_create_by!(title: "Pediatria")
Specialty.find_or_create_by!(title: "Pneumologia")
Specialty.find_or_create_by!(title: "Psiquiatria")
Specialty.find_or_create_by!(title: "Radiologia e Diagnóstico por Imagem")
Specialty.find_or_create_by!(title: "Radioterapia")
Specialty.find_or_create_by!(title: "Reumatologia")
Specialty.find_or_create_by!(title: "Urologia")
